# A reusable Workflow for generating an installation token of a GitHub App. Can be used as a alternative identity/account
# when acting on a repo
# 
# This workflow should and only should be called by others, not act on githuc event

name: Generate GitHub App Token
description: "Generate an installation token for a GitHub App"

inputs:
  app-id:
    description: "The ID of the GitHub App."
    required: true
    type: string
  private-key:
    description: "The private key of the GitHub App."
    required: true
    type: string

outputs:
  token:
    description: "GitHub App installation token"

runs:
  using: "composite"
  steps:
    - name: Generate Token
      id: generate-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}